apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verrazzano-argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/anandf/app-platform-argocd
      targetRevision: main
      path: components/cert-manager
    - repoURL: https://github.com/anandf/app-platform-argocd
      targetRevision: main
      path: components/istio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
