
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          securityContext:
            runAsUser: 1337
            runAsGroup: 1337
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          overlays:
            - kind: Deployment
              name: istio-egressgateway
              patches:
                - path: spec.template.spec.containers.[name:istio-proxy].securityContext
                  value: |
                    privileged: false
                    allowPrivilegeEscalation: false
                    capabilities:
                      drop:
                        - ALL
    ingressGateways:
      - name: istio-ingressgateway
        k8s:
          securityContext:
            runAsUser: 1337
            runAsGroup: 1337
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          overlays:
            - kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.containers.[name:istio-proxy].securityContext
                  value: |
                    privileged: false
                    allowPrivilegeEscalation: false
                    capabilities:
                      drop:
                        - ALL
    pilot:
      k8s:
        securityContext:
          runAsUser: 1337
          runAsGroup: 1337
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        overlays:
          - kind: Deployment
            name: istiod
            patches:
              - path: spec.template.spec.containers.[name:discovery].securityContext
                value: |
                  privileged: false
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL

  # Global values passed through to helm global.yaml.
  # Please keep this in sync with manifests/charts/global.yaml
  values:
      multiCluster:
        enabled: false
      istioNamespace: istio-system
      imagePullPolicy: IfNotPresent
      proxy:
        readinessFailureThreshold: 90
      # enable pod disruption budget for the control plane, which is used to ensure Istio control plane
      # components are gradually upgraded or recovered.
      # pod disruption budget(pdb) is disabled to allow upgrading worker nodes without violating pdb
      defaultPodDisruptionBudget:
        enabled: false

    pilot:
      autoscaleEnabled: false
    gateways:
      istio-egressgateway:
        env:
          # Needed to route traffic via egress gateway if desired.
          ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false

    meshConfig:
      enablePrometheusMerge: false
      defaultConfig:
        proxyMetadata: { }

    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
