apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
         - port: 8000
           expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
        - type: gateway
          properties:
            domain: testsvc.172.18.255.200.nip.io
            class: nginx
            http:
              "/": 8000
