apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  sources:
    - chart: base
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: "1.17.2"
      helm:
        releaseName: istio
    - repoURL: https://github.com/anandf/app-platform-argocd
      targetRevision: main
      path: components/istio/helm-values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
