apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.11.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - values.yaml
    - repoURL: https://github.com/anandf/app-platform-argocd
      targetRevision: main
      path: components/cert-manager/helm-values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
