ingress:
  enabled: true
  labels: {}
  path: /grafana

  # pathType is only for k8s >= 1.1=
  pathType: Prefix

  hosts:
    - '*'
serviceMonitor:
  enabled: true
  path: /metrics
  labels: {}
  interval: 1m
  scheme: http
  tlsConfig: {}
  scrapeTimeout: 30s
  relabelings: []
  targetLabels: []

